<template>
  <v-container fluid>
    <v-card
      class="mt-2 mb-4">
      <v-card-text>
        <span class="black--text mr-2" style="font-size: large">I have a question about...</span>
        <v-chip-group
          v-model="questionCategory"
          color="primary"
          mandatory
          rounded
        >
          <v-chip value="buyer">Buying</v-chip>
          <v-chip value="seller">Selling</v-chip>
        </v-chip-group>
      </v-card-text>
    </v-card>
    <v-expansion-panels>
      <template v-for="(questionLists, category) in questions">
        <template v-for="(questionList, section) in questionLists">
          <template v-if="category === questionCategory">
                        <span style="width: 100%; text-align: left; font-size: large"
                              class="mb-2 mt-4 font-weight-medium">{{section}}</span>
            <v-expansion-panel
              v-for="{question, answer} in questionList"
            >
              <v-expansion-panel-header>
                        <span class="text--primary" style="font-size: large">
                            {{ question }}
                        </span>
              </v-expansion-panel-header>
              <v-expansion-panel-content>
                <span v-html="answer"></span>
              </v-expansion-panel-content>
            </v-expansion-panel>
          </template>
        </template>
      </template>
    </v-expansion-panels>
  </v-container>
</template>

<script>
    export default {
        name: "Faq",
        data() {
            return {
                questionCategory: 'buyer',
                questions:
                    {
                        buyer: {
                            'General questions': [
                                {
                                    question: 'How does buying files work on Prev-U?',
                                    answer: `The seller will first send you a link to a payment page. On this page, you will be shown a preview of each file. This lets you make sure you are satisfied with the content before paying it. The preview is generated by our website with one or many filters applied to the original file (watermark, blur, noise, etc.)<br><br>
                                        'Once the payment is accepted, you will receive the original file.`
                                },
                                {
                                    question: 'Can I get a refund if I\'m not satisfied with my purchase?',
                                    answer: `Because the payment page offers a near full preview of the files, we consider it your responsibility to make sure what you're buying fits your standards. If a preview hides excessively the content of the file, please ask the seller to reduce the intensity of the filters and send you a new link.<br><br>

We will only issue refunds on the very rare case that the seller has maliciously used the preview filters (ex: Applying blur to an already blurred image)<br><br>

If you want to issue a refund request, simply contact us with your transaction id. You can find the transaction id in the email you received after a purchase and on the post-purchase page.`
                                },
                                {
                                    question: 'How do you protect my credit card information?',
                                    answer: `None of these information are sent to or stored on Prev-U's servers. They are directly sent to our payment processor, Stripe, known for its high security standards and compliance.`
                                },
                                {
                                    question: 'What rights do I have over the content I purchase?',
                                    answer: `You have the right to use the content for commercial or non-commercial purposes. The license is non-exclusive. The license does not allow you to resell the original file itself with little or no modification.`
                                },
                                {
                                    question: 'What happens when I purchase files?',
                                    answer: `You will be redirected to a page where you can download a compressed file (.zip) of your purchase. This page will also be available from the purchase confirmation email you will receive. You can also view and download individual files in the 'Bought Items' section for one year.`
                                },
                                {
                                    question: 'How long are my files stored after purchase?',
                                    answer: `Your files will be available for download up to one year after purchase.`
                                },
                            ],
                        },
                        seller: {
                            'Files': [
                                {
                                    question: 'How does file selling work on Prev-U?',
                                    answer: `Click on the "Sell" button on your dashboard.<br>
                                    Upload your files.<br>
                                Customize the preview.<br>
                                Set the price and the currency.<br>
                                Send the url created to your customer.`
                                },
                                {
                                    question: 'What type of files can I sell?',
                                    // answer: 'We handle many image, video and audio formats. We also support GIF, PSD and SVG formats.'
                                    answer: 'We only handle png and jpeg formats. We will soon add other file types. We are open to suggestions!'
                                },
                                {
                                    question: 'What does my customer see when I send him a link?',
                                    answer: 'The customer will see a payment page showing the price of the individual files, the preview generated and some file metadata. Furthermore, the customer will be shown how a similar file would be affected by the same preview filters.'
                                },
                                {
                                    question: 'What happens when my customer purchases a file?',
                                    answer: `He will be redirected to a page where he can download the original files. He will also receive an email with a link to that page.<br>
He can also download files separately in the "Bought Items" section of his profile.<br><br>

The files will be available for download for one year.`
                                },
                                {
                                    question: 'Can I allow my customers to choose the file(s) they want between several ones?',
                                    answer: `Yes, if you sell several files at once, your customer will be able to remove files from his order by unchecking the ones he doesn't want.<br><br>

This can be particularly useful if you want to show several versions of a work you did and let the customer choose the one(s) he prefers.`
                                },
                                {
                                    question: 'Is it possible to choose the currency used to sell my files?',
                                    answer: `Yes, when you are asked to set a price for your Items, you can change the currency.`
                                },
                                {
                                    question: 'Are there restrictions on the files that can be sold on Prev-U?',
                                    answer: `You cannot sell content infringing a copyright, against our terms and conditions or against the law.`
                                },
                            ],
                            'Pricing': [
                                {
                                    question: 'What does it cost to use Prev-U?',
                                    answer: 'Prev-U\'s basic account has no setup fee or no monthly fee, making it ideal for the occasional freelancer. For each transaction on a basic account, a fee of 7% is applied.'
                                }
                            ],
                            'Privacy': [

                                {
                                    question: 'How do you protect banking information and other identity information?',
                                    answer: `None of these information (bank account number, credit card number, address, birth date, SSN, etc.) are sent to or stored on Prev-U's servers. They are directly sent to our payment processor, Stripe, known for its high security standards and compliance.`
                                },
                            ],
                            'Payouts': [

                                {
                                    question: 'How do you manage payouts?',
                                    answer: `The payouts are sent directly to your bank account, without extra fees. The payouts are made on a daily schedule, with a 7-10 days delay.<br><br>
You can track you payouts by clicking on the "payouts" button from your dashboard. You will be redirected to Stripe's secure dashboard.`
                                },
                                {
                                    question: 'What information is required to receive payouts?',
                                    answer: `You need to link a bank account and provide some information required by our payment processor, Stripe. The required information varies depending on your country. However, you always need to provide: your name, date of birth and address.
Some information is not necessary at first and is required only when you reach a certain revenue.`
                                },
                            ]
                        }
                    }
            }
        }
    }
</script>

<style lang="scss" scoped>
</style>
